### ISSUE TITLE
image-pre-processor: support adding noise to depth images

### ISSUE THREAD

**Issue by rib** [glimpse-project/glimpse#6]
Either via externally generated noise images or via builtin noise generators there needs to be more control over the noise applied to depth image.

Currently we simply apply white noise with with a hardcoded amplitude which seemed reasonable when we were mimicking the Tango Zenfone AR camera data, but e.g. if we look at the noise for iPhone X TrueDepth cameras it looks like we should apply some form of perlin noise to mimic the wobbly/wavey nature of the noise we see, maybe with a very low amplitude white noise combined too.

**Comment by Cwiiis** [comment]
This was fixed a long time ago, probably in https://github.com/glimpse-project/glimpse/commit/54e03848fd33b2c3bfe1f27839f6e8f53edb348c
